services:
  App\Command\AbstractCommand:
    abstract: true
    calls:
      - [setLogExtraDataKeeper, ['@Ewll\LogExtraDataBundle\LogExtraDataKeeper']]

  App\Command\UpdateDepoolsListCommand:
    parent: App\Command\AbstractCommand
    arguments:
      - '@logger'
      - '@doctrine.orm.entity_manager'
      - '@App\Ton'
    tags:
      - { name: 'console.command', command: 'depool:list:update' }

  App\Command\UpdateDepoolEventsCommand:
    parent: App\Command\AbstractCommand
    arguments:
      - '@logger'
      - '@doctrine.orm.entity_manager'
      - '@App\Ton'
    tags:
      - { name: 'console.command', command: 'depool:events:update' }

  App\Command\UpdateDepoolNamesCommand:
    parent: App\Command\AbstractCommand
    arguments:
      - '@logger'
      - '@doctrine.orm.entity_manager'
      - '@App\Ton'
      - '%namesContractAddress%'
    tags:
      - { name: 'console.command', command: 'depool:names:update' }

  App\Command\CacheDepoolQueryCommand:
    parent: App\Command\AbstractCommand
    arguments:
      - '@logger'
      - '@doctrine.orm.entity_manager'
      - '%cacheDir%'
      - '@App\Ton'
    tags:
      - { name: 'console.command', command: 'depool:query:cache' }

  App\Command\CompileStatsCommand:
    parent: App\Command\AbstractCommand
    arguments:
      - '@logger'
      - '@doctrine.orm.entity_manager'
      - '@App\Ton'
    tags:
      - { name: 'console.command', command: 'depool:stats:compile' }

  App\Command\FillApyStatsCommand:
    parent: App\Command\AbstractCommand
    arguments:
      - '@logger'
      - '@doctrine.orm.entity_manager'
      - '@App\Ton'
    tags:
      - { name: 'console.command', command: 'depool:stats:fill-apy' }
